name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # or main if your default branch is named "main"
  # You can also specify paths if you want to trigger only on changes in specific files
  # paths:
  #   - '**/*.html'
  #   - '**/*.css'
  #   - '**/*.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/shreyash-static-web:latest

